### ISSUE TITLE
謝辞

### ISSUE THREAD

**Issue by TakumiBaba** [TakumiBaba/master-thesis#28]
適切な人物を忘れずに謝辞るのを忘れない。

**Comment by ymrl** [comment]
<blockquote class="twitter-tweet" lang="en"><p>謝辞、日本語ラップ的に韻を踏んだりしてほしい</p>&mdash; なんどう さねまさ (@ymrl) <a href="https://twitter.com/ymrl/status/552138371980464128">January 5, 2015</a></blockquote>

**Comment by TakumiBaba** [comment]
俺には無理だった
