### ISSUE TITLE
コードが画像なのダサくね？

### ISSUE THREAD

**Issue by ymrl** [TakumiBaba/master-thesis#31]
せめてもうちょっと解像度上げた方がいいのでは。

**Comment by TakumiBaba** [comment]
キレイにシンタックスハイライトしてくれるやつが見つからないので画像にしてます。
ダサイのは思ってたので、他の手法を探してみます。

**Comment by TakumiBaba** [comment]
lstlisting使うようにした。

**Comment by ymrl** [comment]
![LGTM](http://www.lgtm.in/p/Gf1rLYmun)

**Comment by TakumiBaba** [comment]
知見: コードを画像に変更するとページがだいぶ減る
