### ISSUE TITLE
「コンピュータ」と「計算機」

### ISSUE THREAD

**Issue by ymrl** [TakumiBaba/master-thesis#35]
```
$ git grep コンピュータ markdown | wc
     109     275   16475
$ git grep 計算機 markdown | wc
      68     156    9906
```

どっちやねん。（もしかして明確な使い分けがある？）

**Comment by TakumiBaba** [comment]
初期に書いてた部分はコンピュータ、最近は計算機と表記しているので、
計算機が正しいです(タイトルに合わせてる)。
多分、コメントアウトしてる部分に多く存在してると思われます。
気付かずに本文でも使ってそうですが....

**Comment by ymrl** [comment]
background.mdもdesign.mdもけっこうコンピュータって書いてある気がする。
他はまだ見てない。

**Comment by TakumiBaba** [comment]
う、直します....
