### ISSUE TITLE
マニュアルという表現

### ISSUE THREAD

**Issue by TakumiBaba** [TakumiBaba/master-thesis#38]
レシピは手順書だが、マニュアルは手順書というわけではない、という指摘を頂いたので
表現を考える

**Comment by TakumiBaba** [comment]
マニュアル以外の表現がうまく浮かばない

**Comment by shokai** [comment]
インストラクション

**Comment by TakumiBaba** [comment]
shokaiさんありがとうございます！
マニュアルに記述されているようなインストラクション とか？

**Comment by TakumiBaba** [comment]
清水亮著: 教養としてのプログラミング講座 にも
マニュアルはプログラムだって書いてあるし、マニュアルでもいい気がしてきた。

**Comment by TakumiBaba** [comment]
業務マニュアル、とか？

**Comment by TakumiBaba** [comment]
疲れた
